<robot name="my_car_move" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="joint_trans" params="joint_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- every wheel needs a joint -->
    <!-- For adapting this file to your model, you need to change this !!!-->
    <!-- ********************************************************** -->
    <xacro:joint_trans joint_name="base_l_wheel_joint" />
    <xacro:joint_trans joint_name="base_r_wheel_joint" />
    <!-- ********************************************************** -->

    <!-- controller -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <!-- For adapting this file to your model, you need to change this !!!-->
            <!-- ********************************************************** -->
            <leftJoint>base_l_wheel_joint</leftJoint> <!-- left wheel -->
            <rightJoint>base_r_wheel_joint</rightJoint> <!-- rigth wheel -->
            <wheelSeparation>${base_radius * 2}</wheelSeparation> <!-- gap between two wheels -->
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter> 
            <!-- ********************************************************** -->
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic> <!-- control topic -->
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> <!-- odom topic -->
            <!-- For adapting this file to your model, you need to change this !!!-->
            <!-- ********************************************************** -->
            <robotBaseFrame>base_footprint</robotBaseFrame> <!-- root coordinate -->
            <!-- ********************************************************** -->
        </plugin>
    </gazebo>

</robot>