<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- camera -->
    <!-- 1. Parameters -->
    <xacro:property name="camera_length" value="0.02" />
    <xacro:property name="camera_width" value="0.05" />
    <xacro:property name="camera_height" value="0.05" />
    <xacro:property name="camera_mass" value="0.01" />
    <xacro:property name="joint_camera_x" value="0.08" />
    <xacro:property name="joint_camera_y" value="0" />
    <xacro:property name="joint_camera_z" value="${base_length / 2 + camera_height / 2}" />

    <!-- 2. links and joints -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0" />
            </material>
        </visual>
        <!-- **************************************************************************** -->
        <!-- 1. For simulation in gazebo, we must define collision, inertia matrix for every link extraly -->
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>

        <!-- use inertia matrix from the file head.xacro -->
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
        <!-- **************************************************************************** -->
    </link>

    <!-- **************************************************************************** -->
    <!-- 2. For simulation in gazebo, we must define color for every link extraly -->
    <!-- color setting in gazebo -->
    <gazebo reference="camera">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!-- **************************************************************************** -->

    <joint name="camera2base" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0" />

    </joint>



</robot>