<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- ========================================================================================= -->
    <!-- base_footprint   base_link-->
    <xacro:property name="footprint_radius" value="0.001" />
    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length / 2 + lidi}" />

    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="yellow">
                <color rgba="0.8 0.3 0.1 0.5" />
            </material>
        </visual>
    </link>

    <joint name="base_link2base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link"/>
        <!-- h = heigth of car / 2 + gap betweent car and ground = 0.08/2 + 0.015 -->
        <origin xyz="0 0 ${base_joint_z}" />
    </joint>

    <!-- ========================================================================================= -->
    <!-- left_wheel   right_wheel-->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="wheel_joint_z" value="${(base_length / 2 + lidi - wheel_radius) * (-1)}" />

    <!-- wheel_name: left or right -->
    <!-- flag: 1 for left or -1 for right -->
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1.0" />
                </material>
            </visual>
        </link>

        <joint name="${wheel_name}" type="continuous">
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <!--   0.0325-(0.08/2 + 0.015) = -0.0225    -->
            <origin xyz="0 ${0.1 * flag} ${wheel_joint_z}" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <!-- Warning: Joint state with name: “base_l_wheel_joint“ was received but not found in URDF -->
    <!-- Solve: https://blog.csdn.net/qq_41949101/article/details/116665707 -->
    <xacro:wheel_func wheel_name="base_l_wheel_joint" flag = "1" />
    <xacro:wheel_func wheel_name="base_r_wheel_joint" flag = "-1" />

    <!-- ========================================================================================= -->
    <!-- front_wheel   back_wheel-->
    <xacro:property name="small_wheel_radius" value="0.0075" />
    <xacro:property name="small_joint_z" value="${(base_length / 2 + lidi - small_wheel_radius) * (-1)}" />

    <xacro:macro name="small_wheel_func" params="small_wheel_name flag">
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_wheel_radius}" />
                    <!-- radius = 0.015 / 2 = 0.0075 -->
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1.0" />
                </material>
            </visual>
        </link>

        <joint name="${small_wheel_name}_wheel2base_link" type="continuous">
            <parent link="base_link" />
            <child link="${small_wheel_name}_wheel" />
            <!--   0.0075-0.055=-0.0475   -->
            <origin xyz="${0.0925 * flag} 0 ${small_joint_z}" />
            <axis xyz="1 1 1" />
        </joint>
    </xacro:macro>

    <xacro:small_wheel_func small_wheel_name="front" flag = "1" />
    <xacro:small_wheel_func small_wheel_name="back" flag = "-1" />

</robot>